### PR TITLE
v0.9.0

### PR DESCRIPTION
**Pull request by steveberardi**
## Summary
- Added perspective projections (Orthographic, Stereographic) to map plots - many thanks to @bathoorn 
- Zenith plots are now a type of projection for map plots, to support plotting the milky way, constellation borders and more - many thanks to @bathoorn 
- Removed the `visible` style property and instead now you control what is plotted by calling functions on the plot (e.g. `p.stars(mag=8)`) to be more consistent with other plotting frameworks and allow more control over what's plotted and how. For example, now you can do things like plotting very bright stars with a different marker (and sizes, etc) than dimmer stars.
- Optional callables for calculating star size/alpha/color when plotting stars
- Nebula outlines! via [OpenNGC](https://github.com/mattiaverga/OpenNGC)
- Stars are now plotted in order of their calculated size, which prevents "bigger" stars from hiding "smaller" stars
- Added more marker symbols and style extensions

## Preview
```
pip install starplot==0.9.0b1
```
Docs ➡️ https://archives.starplot.dev/0.9.0b/

### CODE REVIEW

**Comment by bathoorn** [comment]
Hi Steve

I will then pull in the latest commits from the v0.9.0 branch.

I have done some work on printing a planisphere calendar ring but I don't
think it will be ready in time. But I can do that for the next release.

I also did some work on not printing things that are not visible. So will
check if that fits in with your latest changes.

Kind regards,
Ronnie

**Comment by steveberardi** [comment]
@bathoorn when I merged this PR last night, I was hoping it would've added you as a "Contributor" on the GH repository page, but it didn't 😞  I'm guessing cause I did a "Squash & Merge" -- GH did add you as a contributor on the release page though 🤔 

Anyway, I apologize. I greatly appreciate the contribution you made for this release, so just wanted to make sure you were recognized on the repo. If you want, I _think_ you could open a PR to main from your fork and when I merge that it'll add you as a contributor. You could just add an empty file or comment or something in the PR.

**Comment by bathoorn** [comment]
No worries, thanks for the heads up!

And my plan is to work on the calendar ring for the planisphere. So there
will be other contributions where we can get it to work :)

**Comment by steveberardi** [comment]
@bathoorn sounds good, thanks so much for your understanding!

**Pull request merged**
